import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Proxy for sendrawtransaction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Proxy for sendrawtransaction json rpc commands
        </h1>

        <p className={styles.description}>
          Get your transactions on chain the lazy way. If you normally do:
          <code className={styles.code}>bitcoin-cli sendrawtransaction 01000...</code>
          then this is the tool for you.
        </p>
      </main>

      <footer className={styles.footer}>
        Run by Bitcoin Association Engineering Team as an interim solution.
        Please adopt an SPV LiteClient approach for the proper scaling architecture.
        <a href={'https://docs.bitcoinsv.io'}>LiteClient Documentation</a>
      </footer>
    </div>
  )
}
